[package]
name = "galileo-osnma"
version = "0.1.0"
edition = "2021"
authors = ["Daniel Estevez <daniel@destevez.net>"]
description = "Galileo OSNMA (Open Service Navigation Message Authentication)"
license = "MIT OR Apache-2.0"

publish = false

[features]
# Galmon protobuf transport format support
galmon = ["bytes", "prost", "prost-build", "std"]
std = []
pem = ["ecdsa/pkcs8", "spki"]

[dependencies]
aes = "0.8"
bytes = { version = "1.1", optional = true }
cmac = "0.7"
ecdsa = "0.13"
env_logger = { version = "0.9", optional = true }
log = "0.4"
p256 = { version = "0.10", features = ["ecdsa"] }
prost = { version = "0.9", optional = true }
sha2 = "0.10"
sha3 = "0.10"
spki = { version = "0.5", optional = true, features = ["pem"] }

[build-dependencies]
prost-build = { version = "0.9", optional = true }

[dev-dependencies]
hex-literal = "0.3"
