[package]
name = "galileo-osnma"
version = "0.1.0"
edition = "2021"
authors = ["Daniel Estevez <daniel@destevez.net>"]
description = "Galileo OSNMA (Open Service Navigation Message Authentication)"
license = "MIT OR Apache-2.0"

publish = false

[features]
# Galmon protobuf transport format support
galmon = ["bytes", "prost", "prost-build"]

[dependencies]
bytes = { version = "1.1", optional = true }
env_logger = { version = "0.9", optional = true }
log = "0.4"
prost = { version = "0.9", optional = true }

[build-dependencies]
prost-build = { version = "0.9", optional = true }

