name: 'pycodestyle'

on: [push, pull_request]

jobs:
  pycodestyle:
    name: pycodestyle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install pycodestyle with pip
      run: pip install pycodestyle
    - name: Run pycodestyle
      run: pycodestyle .
