name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: cargo fmt --check
    - name: Clippy
      run: cargo clippy
    - name: Clippy (Galmon)
      run: cargo clippy --features galmon 
    - name: Build
      run: cargo build --verbose  
    - name: Run tests
      run: cargo test --verbose
    - name: Build (Galmon)
      run: cargo build --verbose --features galmon
    - name: Run tests (Galmon)
      run: cargo test --verbose --features galmon
